//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlourFlowDesktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlourFlowDesktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ingredient.
        /// </summary>
        public static string AddIngredientButton {
            get {
                return ResourceManager.GetString("AddIngredientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Order.
        /// </summary>
        public static string AddOrderButton {
            get {
                return ResourceManager.GetString("AddOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string AddSupplierButton {
            get {
                return ResourceManager.GetString("AddSupplierButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerNameHeader {
            get {
                return ResourceManager.GetString("CustomerNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name:.
        /// </summary>
        public static string CustomerNameLabel {
            get {
                return ResourceManager.GetString("CustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string IDHeader {
            get {
                return ResourceManager.GetString("IDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient ID.
        /// </summary>
        public static string IngredientIDHeader {
            get {
                return ResourceManager.GetString("IngredientIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Name:.
        /// </summary>
        public static string IngredientNameLabel {
            get {
                return ResourceManager.GetString("IngredientNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string IngredientsTab {
            get {
                return ResourceManager.GetString("IngredientsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlourFlow.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDateHeader {
            get {
                return ResourceManager.GetString("OrderDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date:.
        /// </summary>
        public static string OrderDateLabel {
            get {
                return ResourceManager.GetString("OrderDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderIDHeader {
            get {
                return ResourceManager.GetString("OrderIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID:.
        /// </summary>
        public static string OrderIDLabel {
            get {
                return ResourceManager.GetString("OrderIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrdersTab {
            get {
                return ResourceManager.GetString("OrdersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceHeader {
            get {
                return ResourceManager.GetString("PriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per Unit:.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityHeader {
            get {
                return ResourceManager.GetString("QuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        public static string SupplierIDHeader {
            get {
                return ResourceManager.GetString("SupplierIDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string SupplierNameHeader {
            get {
                return ResourceManager.GetString("SupplierNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name:.
        /// </summary>
        public static string SupplierNameLabel {
            get {
                return ResourceManager.GetString("SupplierNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string SuppliersTab {
            get {
                return ResourceManager.GetString("SuppliersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitHeader {
            get {
                return ResourceManager.GetString("UnitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:.
        /// </summary>
        public static string UnitLabel {
            get {
                return ResourceManager.GetString("UnitLabel", resourceCulture);
            }
        }
    }
}
